In [1]:
!pip install transformers datasets torch accelerate

Collecting transformers
  Downloading transformers-5.6.2-py3-none-any.whl.metadata (33 kB)
Collecting datasets
  Downloading datasets-4.8.4-py3-none-any.whl.metadata (19 kB)
Collecting torch
  Downloading torch-2.11.0-cp313-cp313-win_amd64.whl.metadata (29 kB)
Collecting accelerate
  Downloading accelerate-1.13.0-py3-none-any.whl.metadata (19 kB)
Collecting huggingface-hub<2.0,>=1.5.0 (from transformers)
  Downloading huggingface_hub-1.12.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in c:\users\moham\anaconda3\lib\site-packages (from transformers) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\users\moham\anaconda3\lib\site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\moham\anaconda3\lib\site-packages (from transformers) (6.0.3)
Collecting regex>=2025.10.22 (from transformers)
  Downloading regex-2026.4.4-cp313-cp313-win_amd64.whl.metadata (41 kB)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Downloading tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Requirement already satisfied: typer in c:\users\moham\anaconda3\lib\site-packages (from transformers) (0.20.0)
Collecting safetensors>=0.4.3 (from transformers)
  Downloading safetensors-0.7.0-cp38-abi3-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: tqdm>=4.27 in c:\users\moham\anaconda3\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: filelock>=3.10.0 in c:\users\moham\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\moham\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.10.0)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Downloading hf_xet-1.4.3-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\moham\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\moham\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in c:\users\moham\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.10.0)
Requirement already satisfied: certifi in c:\users\moham\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in c:\users\moham\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\moham\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\moham\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: pyarrow>=21.0.0 in c:\users\moham\anaconda3\lib\site-packages (from datasets) (21.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in c:\users\moham\anaconda3\lib\site-packages (from datasets) (0.4.0)
Requirement already satisfied: pandas in c:\users\moham\anaconda3\lib\site-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in c:\users\moham\anaconda3\lib\site-packages (from datasets) (2.32.5)
Collecting xxhash (from datasets)
  Downloading xxhash-3.7.0-cp313-cp313-win_amd64.whl.metadata (13 kB)
Collecting multiprocess<0.70.20 (from datasets)
  Downloading multiprocess-0.70.19-py313-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\moham\anaconda3\lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.2)
Collecting dill<0.4.2,>=0.3.0 (from datasets)
  Downloading dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: setuptools<82 in c:\users\moham\anaconda3\lib\site-packages (from torch) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\moham\anaconda3\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\moham\anaconda3\lib\site-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in c:\users\moham\anaconda3\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: psutil in c:\users\moham\anaconda3\lib\site-packages (from accelerate) (7.0.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\moham\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\moham\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\moham\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\moham\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\moham\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\moham\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\moham\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\moham\anaconda3\lib\site-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\moham\anaconda3\lib\site-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\moham\anaconda3\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: colorama in c:\users\moham\anaconda3\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\moham\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\moham\anaconda3\lib\site-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\moham\anaconda3\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\moham\anaconda3\lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\moham\anaconda3\lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\moham\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.0.0 in c:\users\moham\anaconda3\lib\site-packages (from typer->transformers) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\moham\anaconda3\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\moham\anaconda3\lib\site-packages (from typer->transformers) (14.2.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\moham\anaconda3\lib\site-packages (from rich>=10.11.0->typer->transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\moham\anaconda3\lib\site-packages (from rich>=10.11.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\moham\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->transformers) (0.1.2)
Downloading transformers-5.6.2-py3-none-any.whl (10.4 MB)
   ---------------------------------------- 0.0/10.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.4 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.4 MB ? eta -:--:--
   -- ------------------------------------- 0.5/10.4 MB 1.2 MB/s eta 0:00:09
   --- ------------------------------------ 0.8/10.4 MB 1.2 MB/s eta 0:00:08
   ---- ----------------------------------- 1.0/10.4 MB 1.3 MB/s eta 0:00:08
   ----- ---------------------------------- 1.3/10.4 MB 1.2 MB/s eta 0:00:08
   ------ --------------------------------- 1.6/10.4 MB 1.3 MB/s eta 0:00:08
   ------- -------------------------------- 1.8/10.4 MB 1.3 MB/s eta 0:00:07
   ------- -------------------------------- 1.8/10.4 MB 1.3 MB/s eta 0:00:07
   -------- ------------------------------- 2.1/10.4 MB 1.0 MB/s eta 0:00:08
   -------- ------------------------------- 2.1/10.4 MB 1.0 MB/s eta 0:00:08
   --------- ------------------------------ 2.4/10.4 MB 996.6 kB/s eta 0:00:09
   ---------- ----------------------------- 2.6/10.4 MB 1.0 MB/s eta 0:00:08
   ----------- ---------------------------- 2.9/10.4 MB 1.0 MB/s eta 0:00:08
   ------------ --------------------------- 3.1/10.4 MB 1.1 MB/s eta 0:00:07
   ------------ --------------------------- 3.1/10.4 MB 1.1 MB/s eta 0:00:07
   ------------- -------------------------- 3.4/10.4 MB 1.0 MB/s eta 0:00:07
   -------------- ------------------------- 3.7/10.4 MB 1.0 MB/s eta 0:00:07
   ---------------- ----------------------- 4.2/10.4 MB 1.1 MB/s eta 0:00:06
   ----------------- ---------------------- 4.5/10.4 MB 1.1 MB/s eta 0:00:06
   ----------------- ---------------------- 4.5/10.4 MB 1.1 MB/s eta 0:00:06
   ------------------ --------------------- 4.7/10.4 MB 1.1 MB/s eta 0:00:06
   -------------------- ------------------- 5.2/10.4 MB 1.1 MB/s eta 0:00:05
   --------------------- ------------------ 5.5/10.4 MB 1.1 MB/s eta 0:00:05
   ---------------------- ----------------- 5.8/10.4 MB 1.2 MB/s eta 0:00:04
   ------------------------ --------------- 6.3/10.4 MB 1.2 MB/s eta 0:00:04
   ------------------------- -------------- 6.6/10.4 MB 1.2 MB/s eta 0:00:04
   --------------------------- ------------ 7.1/10.4 MB 1.3 MB/s eta 0:00:03
   ----------------------------- ---------- 7.6/10.4 MB 1.3 MB/s eta 0:00:03
   ------------------------------- -------- 8.1/10.4 MB 1.3 MB/s eta 0:00:02
   ------------------------------- -------- 8.1/10.4 MB 1.3 MB/s eta 0:00:02
   ---------------------------------- ----- 8.9/10.4 MB 1.4 MB/s eta 0:00:02
   ----------------------------------- ---- 9.2/10.4 MB 1.4 MB/s eta 0:00:01
   ------------------------------------- -- 9.7/10.4 MB 1.4 MB/s eta 0:00:01
   -------------------------------------- - 10.0/10.4 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 10.4/10.4 MB 1.4 MB/s  0:00:07
Downloading huggingface_hub-1.12.0-py3-none-any.whl (646 kB)
   ---------------------------------------- 0.0/646.8 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/646.8 kB ? eta -:--:--
   ---------------------------------------- 646.8/646.8 kB 1.9 MB/s  0:00:00
Downloading hf_xet-1.4.3-cp37-abi3-win_amd64.whl (3.7 MB)
   ---------------------------------------- 0.0/3.7 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/3.7 MB 2.7 MB/s eta 0:00:02
   ----------- ---------------------------- 1.0/3.7 MB 2.6 MB/s eta 0:00:01
   ----------------- ---------------------- 1.6/3.7 MB 2.6 MB/s eta 0:00:01
   ------------------- -------------------- 1.8/3.7 MB 2.5 MB/s eta 0:00:01
   ------------------------- -------------- 2.4/3.7 MB 2.3 MB/s eta 0:00:01
   ---------------------------- ----------- 2.6/3.7 MB 2.2 MB/s eta 0:00:01
   ------------------------------------- -- 3.4/3.7 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------- 3.7/3.7 MB 2.3 MB/s  0:00:01
Downloading tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.7 MB 2.7 MB/s eta 0:00:01
   ----------- ---------------------------- 0.8/2.7 MB 1.6 MB/s eta 0:00:02
   ------------------- -------------------- 1.3/2.7 MB 2.1 MB/s eta 0:00:01
   -------------------------- ------------- 1.8/2.7 MB 2.2 MB/s eta 0:00:01
   -------------------------------------- - 2.6/2.7 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 2.4 MB/s  0:00:01
Downloading datasets-4.8.4-py3-none-any.whl (526 kB)
   ---------------------------------------- 0.0/527.0 kB ? eta -:--:--
   ---------------------------------------- 527.0/527.0 kB 3.4 MB/s  0:00:00
Downloading multiprocess-0.70.19-py313-none-any.whl (156 kB)
Downloading dill-0.4.1-py3-none-any.whl (120 kB)
Downloading torch-2.11.0-cp313-cp313-win_amd64.whl (114.6 MB)
   ---------------------------------------- 0.0/114.6 MB ? eta -:--:--
   ---------------------------------------- 0.5/114.6 MB 4.0 MB/s eta 0:00:29
   ---------------------------------------- 1.0/114.6 MB 3.2 MB/s eta 0:00:36
    --------------------------------------- 1.8/114.6 MB 2.8 MB/s eta 0:00:40
    --------------------------------------- 2.4/114.6 MB 2.8 MB/s eta 0:00:40
   - -------------------------------------- 2.9/114.6 MB 2.9 MB/s eta 0:00:40
   - -------------------------------------- 3.7/114.6 MB 2.9 MB/s eta 0:00:39
   - -------------------------------------- 4.2/114.6 MB 2.9 MB/s eta 0:00:38
   - -------------------------------------- 4.7/114.6 MB 2.9 MB/s eta 0:00:38
   - -------------------------------------- 5.5/114.6 MB 2.9 MB/s eta 0:00:38
   -- ------------------------------------- 6.0/114.6 MB 2.9 MB/s eta 0:00:38
   -- ------------------------------------- 6.8/114.6 MB 2.9 MB/s eta 0:00:38
   -- ------------------------------------- 7.3/114.6 MB 2.9 MB/s eta 0:00:37
   -- ------------------------------------- 7.9/114.6 MB 2.9 MB/s eta 0:00:38
   --- ------------------------------------ 8.7/114.6 MB 2.9 MB/s eta 0:00:37
   --- ------------------------------------ 9.2/114.6 MB 2.9 MB/s eta 0:00:37
   --- ------------------------------------ 9.7/114.6 MB 2.9 MB/s eta 0:00:37
   --- ------------------------------------ 10.5/114.6 MB 2.9 MB/s eta 0:00:36
   --- ------------------------------------ 11.0/114.6 MB 2.9 MB/s eta 0:00:36
   ---- ----------------------------------- 11.5/114.6 MB 2.9 MB/s eta 0:00:36
   ---- ----------------------------------- 12.3/114.6 MB 2.9 MB/s eta 0:00:35
   ---- ----------------------------------- 12.8/114.6 MB 2.9 MB/s eta 0:00:35
   ---- ----------------------------------- 13.4/114.6 MB 2.9 MB/s eta 0:00:35
   ---- ----------------------------------- 14.2/114.6 MB 2.9 MB/s eta 0:00:35
   ----- ---------------------------------- 14.9/114.6 MB 2.9 MB/s eta 0:00:34
   ----- ---------------------------------- 15.5/114.6 MB 2.9 MB/s eta 0:00:34
   ----- ---------------------------------- 16.0/114.6 MB 2.9 MB/s eta 0:00:34
   ----- ---------------------------------- 16.8/114.6 MB 2.9 MB/s eta 0:00:34
   ----- ---------------------------------- 17.0/114.6 MB 2.9 MB/s eta 0:00:34
   ------ --------------------------------- 17.3/114.6 MB 2.8 MB/s eta 0:00:35
   ------ --------------------------------- 17.3/114.6 MB 2.8 MB/s eta 0:00:35
   ------ --------------------------------- 17.6/114.6 MB 2.7 MB/s eta 0:00:37
   ------ --------------------------------- 17.8/114.6 MB 2.7 MB/s eta 0:00:37
   ------ --------------------------------- 17.8/114.6 MB 2.7 MB/s eta 0:00:37
   ------ --------------------------------- 17.8/114.6 MB 2.7 MB/s eta 0:00:37
   ------ --------------------------------- 17.8/114.6 MB 2.7 MB/s eta 0:00:37
   ------ --------------------------------- 18.6/114.6 MB 2.5 MB/s eta 0:00:40
   ------ --------------------------------- 19.1/114.6 MB 2.4 MB/s eta 0:00:40
   ------ --------------------------------- 19.7/114.6 MB 2.4 MB/s eta 0:00:39
   ------ --------------------------------- 19.9/114.6 MB 2.4 MB/s eta 0:00:39
   ------- -------------------------------- 20.2/114.6 MB 2.4 MB/s eta 0:00:39
   ------- -------------------------------- 20.7/114.6 MB 2.4 MB/s eta 0:00:40
   ------- -------------------------------- 21.2/114.6 MB 2.4 MB/s eta 0:00:40
   ------- -------------------------------- 21.5/114.6 MB 2.4 MB/s eta 0:00:39
   ------- -------------------------------- 22.0/114.6 MB 2.4 MB/s eta 0:00:39
   ------- -------------------------------- 22.5/114.6 MB 2.4 MB/s eta 0:00:39
   -------- ------------------------------- 23.1/114.6 MB 2.4 MB/s eta 0:00:39
   -------- ------------------------------- 23.1/114.6 MB 2.4 MB/s eta 0:00:39
   -------- ------------------------------- 23.6/114.6 MB 2.3 MB/s eta 0:00:40
   -------- ------------------------------- 23.9/114.6 MB 2.3 MB/s eta 0:00:40
   -------- ------------------------------- 24.6/114.6 MB 2.3 MB/s eta 0:00:39
   -------- ------------------------------- 25.2/114.6 MB 2.3 MB/s eta 0:00:39
   -------- ------------------------------- 25.7/114.6 MB 2.3 MB/s eta 0:00:39
   --------- ------------------------------ 26.2/114.6 MB 2.3 MB/s eta 0:00:38
   --------- ------------------------------ 26.7/114.6 MB 2.3 MB/s eta 0:00:38
   --------- ------------------------------ 27.5/114.6 MB 2.4 MB/s eta 0:00:37
   --------- ------------------------------ 27.8/114.6 MB 2.4 MB/s eta 0:00:37
   --------- ------------------------------ 28.0/114.6 MB 2.3 MB/s eta 0:00:38
   --------- ------------------------------ 28.0/114.6 MB 2.3 MB/s eta 0:00:38
   --------- ------------------------------ 28.6/114.6 MB 2.3 MB/s eta 0:00:38
   ---------- ----------------------------- 28.8/114.6 MB 2.3 MB/s eta 0:00:38
   ---------- ----------------------------- 29.6/114.6 MB 2.3 MB/s eta 0:00:37
   ---------- ----------------------------- 30.4/114.6 MB 2.3 MB/s eta 0:00:37
   ---------- ----------------------------- 30.9/114.6 MB 2.3 MB/s eta 0:00:36
   ---------- ----------------------------- 31.5/114.6 MB 2.3 MB/s eta 0:00:36
   ----------- ---------------------------- 32.2/114.6 MB 2.3 MB/s eta 0:00:36
   ----------- ---------------------------- 32.8/114.6 MB 2.3 MB/s eta 0:00:35
   ----------- ---------------------------- 33.3/114.6 MB 2.4 MB/s eta 0:00:35
   ----------- ---------------------------- 34.1/114.6 MB 2.4 MB/s eta 0:00:35
   ------------ --------------------------- 34.6/114.6 MB 2.4 MB/s eta 0:00:34
   ------------ --------------------------- 35.4/114.6 MB 2.4 MB/s eta 0:00:34
   ------------ --------------------------- 35.9/114.6 MB 2.4 MB/s eta 0:00:33
   ------------ --------------------------- 36.7/114.6 MB 2.4 MB/s eta 0:00:33
   ------------ --------------------------- 37.2/114.6 MB 2.4 MB/s eta 0:00:33
   ------------- -------------------------- 37.7/114.6 MB 2.4 MB/s eta 0:00:32
   ------------- -------------------------- 38.3/114.6 MB 2.4 MB/s eta 0:00:32
   ------------- -------------------------- 39.1/114.6 MB 2.4 MB/s eta 0:00:32
   ------------- -------------------------- 39.6/114.6 MB 2.4 MB/s eta 0:00:31
   ------------- -------------------------- 39.6/114.6 MB 2.4 MB/s eta 0:00:31
   -------------- ------------------------- 40.1/114.6 MB 2.4 MB/s eta 0:00:31
   -------------- ------------------------- 40.1/114.6 MB 2.4 MB/s eta 0:00:31
   -------------- ------------------------- 40.4/114.6 MB 2.4 MB/s eta 0:00:32
   -------------- ------------------------- 40.4/114.6 MB 2.4 MB/s eta 0:00:32
   -------------- ------------------------- 40.6/114.6 MB 2.3 MB/s eta 0:00:32
   -------------- ------------------------- 40.6/114.6 MB 2.3 MB/s eta 0:00:32
   -------------- ------------------------- 41.2/114.6 MB 2.3 MB/s eta 0:00:33
   -------------- ------------------------- 41.7/114.6 MB 2.3 MB/s eta 0:00:32
   -------------- ------------------------- 42.2/114.6 MB 2.3 MB/s eta 0:00:32
   -------------- ------------------------- 42.5/114.6 MB 2.3 MB/s eta 0:00:32
   -------------- ------------------------- 42.7/114.6 MB 2.3 MB/s eta 0:00:32

In [4]:
from datasets import load_dataset
import pandas as pd

# 1. Load the dataset with the new security override
print("Downloading the Empathetic Dialogues dataset...")
dataset = load_dataset("empathetic_dialogues", trust_remote_code=True)

# 2. Let's look at the training data specifically
train_data = dataset['train']

# 3. Convert a tiny slice to a pandas dataframe just so we can read it easily
df_preview = pd.DataFrame(train_data[:5])

print("\nDataset loaded successfully! Here are the first few rows:")
df_preview[['context', 'prompt', 'utterance']]

`trust_remote_code` is not supported anymore.
Please check that the Hugging Face dataset 'empathetic_dialogues' isn't based on a loading script and remove `trust_remote_code`.
If the dataset is based on a loading script, please ask the dataset author to remove it and convert it to a standard format like Parquet.

Downloading the Empathetic Dialogues dataset...

RuntimeError: Dataset scripts are no longer supported, but found empathetic_dialogues.py

In [5]:
!pip install datasets==3.6.0

Collecting datasets==3.6.0
  Downloading datasets-3.6.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in c:\users\moham\anaconda3\lib\site-packages (from datasets==3.6.0) (3.20.0)
Requirement already satisfied: numpy>=1.17 in c:\users\moham\anaconda3\lib\site-packages (from datasets==3.6.0) (2.3.5)
Requirement already satisfied: pyarrow>=15.0.0 in c:\users\moham\anaconda3\lib\site-packages (from datasets==3.6.0) (21.0.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets==3.6.0)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in c:\users\moham\anaconda3\lib\site-packages (from datasets==3.6.0) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in c:\users\moham\anaconda3\lib\site-packages (from datasets==3.6.0) (2.32.5)
Requirement already satisfied: tqdm>=4.66.3 in c:\users\moham\anaconda3\lib\site-packages (from datasets==3.6.0) (4.67.1)
Requirement already satisfied: xxhash in c:\users\moham\anaconda3\lib\site-packages (from datasets==3.6.0) (3.7.0)
Collecting multiprocess<0.70.17 (from datasets==3.6.0)
  Downloading multiprocess-0.70.16-py312-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2025.3.0,>=2023.1.0 (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0)
  Downloading fsspec-2025.3.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: huggingface-hub>=0.24.0 in c:\users\moham\anaconda3\lib\site-packages (from datasets==3.6.0) (1.12.0)
Requirement already satisfied: packaging in c:\users\moham\anaconda3\lib\site-packages (from datasets==3.6.0) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\moham\anaconda3\lib\site-packages (from datasets==3.6.0) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\moham\anaconda3\lib\site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0) (3.13.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\moham\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\moham\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\moham\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\moham\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\moham\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\moham\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\moham\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0) (1.22.0)
Requirement already satisfied: idna>=2.0 in c:\users\moham\anaconda3\lib\site-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0) (3.11)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\moham\anaconda3\lib\site-packages (from huggingface-hub>=0.24.0->datasets==3.6.0) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\moham\anaconda3\lib\site-packages (from huggingface-hub>=0.24.0->datasets==3.6.0) (0.28.1)
Requirement already satisfied: typer in c:\users\moham\anaconda3\lib\site-packages (from huggingface-hub>=0.24.0->datasets==3.6.0) (0.20.0)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\moham\anaconda3\lib\site-packages (from huggingface-hub>=0.24.0->datasets==3.6.0) (4.15.0)
Requirement already satisfied: anyio in c:\users\moham\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets==3.6.0) (4.10.0)
Requirement already satisfied: certifi in c:\users\moham\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets==3.6.0) (2026.4.22)
Requirement already satisfied: httpcore==1.* in c:\users\moham\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets==3.6.0) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\moham\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets==3.6.0) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\moham\anaconda3\lib\site-packages (from requests>=2.32.2->datasets==3.6.0) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\moham\anaconda3\lib\site-packages (from requests>=2.32.2->datasets==3.6.0) (2.5.0)
Requirement already satisfied: colorama in c:\users\moham\anaconda3\lib\site-packages (from tqdm>=4.66.3->datasets==3.6.0) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\moham\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets==3.6.0) (1.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\moham\anaconda3\lib\site-packages (from pandas->datasets==3.6.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\moham\anaconda3\lib\site-packages (from pandas->datasets==3.6.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\moham\anaconda3\lib\site-packages (from pandas->datasets==3.6.0) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\moham\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets==3.6.0) (1.17.0)
Requirement already satisfied: click>=8.0.0 in c:\users\moham\anaconda3\lib\site-packages (from typer->huggingface-hub>=0.24.0->datasets==3.6.0) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\moham\anaconda3\lib\site-packages (from typer->huggingface-hub>=0.24.0->datasets==3.6.0) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\moham\anaconda3\lib\site-packages (from typer->huggingface-hub>=0.24.0->datasets==3.6.0) (14.2.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\moham\anaconda3\lib\site-packages (from rich>=10.11.0->typer->huggingface-hub>=0.24.0->datasets==3.6.0) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\moham\anaconda3\lib\site-packages (from rich>=10.11.0->typer->huggingface-hub>=0.24.0->datasets==3.6.0) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\moham\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->huggingface-hub>=0.24.0->datasets==3.6.0) (0.1.2)
Downloading datasets-3.6.0-py3-none-any.whl (491 kB)
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
Downloading fsspec-2025.3.0-py3-none-any.whl (193 kB)
Downloading multiprocess-0.70.16-py312-none-any.whl (146 kB)
Installing collected packages: fsspec, dill, multiprocess, datasets

  Attempting uninstall: fsspec

    Found existing installation: fsspec 2025.10.0

    Uninstalling fsspec-2025.10.0:

      Successfully uninstalled fsspec-2025.10.0

   ---------------------------------------- 0/4 [fsspec]
   ---------------------------------------- 0/4 [fsspec]
   ---------------------------------------- 0/4 [fsspec]
  Attempting uninstall: dill
   ---------------------------------------- 0/4 [fsspec]
    Found existing installation: dill 0.4.1
   ---------------------------------------- 0/4 [fsspec]
    Uninstalling dill-0.4.1:
   ---------------------------------------- 0/4 [fsspec]
      Successfully uninstalled dill-0.4.1
   ---------------------------------------- 0/4 [fsspec]
   ---------- ----------------------------- 1/4 [dill]
   ---------- ----------------------------- 1/4 [dill]
   ---------- ----------------------------- 1/4 [dill]
  Attempting uninstall: multiprocess
   ---------- ----------------------------- 1/4 [dill]
    Found existing installation: multiprocess 0.70.19
   ---------- ----------------------------- 1/4 [dill]
    Uninstalling multiprocess-0.70.19:
   ---------- ----------------------------- 1/4 [dill]
      Successfully uninstalled multiprocess-0.70.19
   ---------- ----------------------------- 1/4 [dill]
   -------------------- ------------------- 2/4 [multiprocess]
   -------------------- ------------------- 2/4 [multiprocess]
   -------------------- ------------------- 2/4 [multiprocess]
  Attempting uninstall: datasets
   -------------------- ------------------- 2/4 [multiprocess]
    Found existing installation: datasets 4.8.4
   -------------------- ------------------- 2/4 [multiprocess]
   ------------------------------ --------- 3/4 [datasets]
    Uninstalling datasets-4.8.4:
   ------------------------------ --------- 3/4 [datasets]
      Successfully uninstalled datasets-4.8.4
   ------------------------------ --------- 3/4 [datasets]
   ------------------------------ --------- 3/4 [datasets]
   ------------------------------ --------- 3/4 [datasets]
   ------------------------------ --------- 3/4 [datasets]
   ------------------------------ --------- 3/4 [datasets]
   ------------------------------ --------- 3/4 [datasets]
   ------------------------------ --------- 3/4 [datasets]
   ---------------------------------------- 4/4 [datasets]

Successfully installed datasets-3.6.0 dill-0.3.8 fsspec-2025.3.0 multiprocess-0.70.16

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
s3fs 2025.10.0 requires fsspec==2025.10.0, but you have fsspec 2025.3.0 which is incompatible.

In [1]:
from datasets import load_dataset
import pandas as pd

# 1. Load the dataset with the security override (which works on datasets v3.6.0!)
print("Downloading the Empathetic Dialogues dataset...")
dataset = load_dataset("empathetic_dialogues", trust_remote_code=True)

# 2. Let's look at the training data specifically
train_data = dataset['train']

# 3. Convert a tiny slice to a pandas dataframe just so we can read it easily
df_preview = pd.DataFrame(train_data[:5])

print("\nDataset loaded successfully! Here are the first few rows:")
df_preview[['context', 'prompt', 'utterance']]

Downloading the Empathetic Dialogues dataset...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Downloading data:   0%|          | 0.00/28.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/76673 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/12030 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/10943 [00:00<?, ? examples/s]

Dataset loaded successfully! Here are the first few rows:

,context,prompt,utterance
0,sentimental,I remember going to the fireworks with my best...,I remember going to see the fireworks with my ...
1,sentimental,I remember going to the fireworks with my best...,Was this a friend you were in love with_comma_...
2,sentimental,I remember going to the fireworks with my best...,This was a best friend. I miss her.
3,sentimental,I remember going to the fireworks with my best...,Where has she gone?
4,sentimental,I remember going to the fireworks with my best...,We no longer talk.

In [4]:
from transformers import AutoModelForCausalLM, TrainingArguments, Trainer, DataCollatorForLanguageModeling

# 1. Load the actual AI "brain" (DistilGPT2)
print("Loading the DistilGPT2 model...")
model = AutoModelForCausalLM.from_pretrained("distilgpt2")

# 2. Set up the training rules
# We use small numbers here so it runs quickly on your local computer!
training_args = TrainingArguments(
    output_dir="./mental_health_bot", # Where to save the finished brain
    num_train_epochs=1,               # Read through the data 1 time
    per_device_train_batch_size=4,    # Learn 4 conversations at a time
    save_steps=10000,
    save_total_limit=2,
)

# 3. Create a data collator (this hands the tokens to the model in neat batches)
data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer, 
    mlm=False, # False because we are generating text, not filling in blanks
)

# 4. Set up the Trainer engine
trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=tokenized_datasets,
)

# 5. START TRAINING!
print("Starting the training process... Grab a quick snack, this might take a few minutes!")
trainer.train()

print("Training complete! You have successfully fine-tuned your own LLM!")

Loading the DistilGPT2 model...

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

Starting the training process... Grab a quick snack, this might take a few minutes!

C:\Users\moham\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
[transformers] `loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training complete! You have successfully fine-tuned your own LLM!

In [6]:
from transformers import pipeline

# 1. Set up a text-generation pipeline using the model currently in memory!
print("Waking up your new AI assistant...")
# Notice we changed model="./mental_health_bot" to just model=model
my_chatbot = pipeline("text-generation", model=model, tokenizer=tokenizer)

# 2. Give it a test prompt (formatted exactly how we trained it)
test_prompt = "User (anxious): I have a huge presentation tomorrow and I am terrified I will mess it up.\nBot:"

# 3. Generate the AI's response
response = my_chatbot(test_prompt, max_new_tokens=40, pad_token_id=tokenizer.eos_token_id)

# 4. Print the result!
print("\n--- Chatbot Test ---")
print(response[0]['generated_text'])

[transformers] Passing `generation_config` together with generation-related arguments=({'max_new_tokens', 'pad_token_id'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Both `max_new_tokens` (=40) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Waking up your new AI assistant...

--- Chatbot Test ---
User (anxious): I have a huge presentation tomorrow and I am terrified I will mess it up.
Bot: I am afraid it will be a long day!
Bot: I am sure it will be a long day!
Bot: You are always a good friend and look forward to getting on

## Task 5 Conclusion & Insights

After successfully loading and tokenizing a subset of the Facebook 'Empathetic Dialogues' dataset, we fine-tuned a pre-trained DistilGPT2 Large Language Model locally.

**Key Findings:**
* The model successfully learned the structural formatting of the training data (recognizing the `User (emotion): ... \nBot:` prompt pattern).
* Due to local hardware constraints, the model was trained on a highly reduced dataset (500 examples) for only 1 epoch.
* As a result, while the model generates structurally formatted text, the semantic quality and depth of empathy remain basic. To achieve production-level conversational empathy, the model would require training on the full 76,000+ row dataset across multiple epochs using cloud GPU infrastructure (like AWS or Google Colab).